### ISSUE TITLE
问题和解答

### ISSUE THREAD

**Issue by yWillow** [TangGolang/TangGo#1]
如果你有任何问题，你都可以在此界面提出，我们会及时回复你。

**Comment by YiLou-tfy** [comment]
![image](https://github.com/TangGolang/TangGo/assets/63778420/41d469cd-6dc1-4c9f-a457-be4b10b0e091)
类似从fofa导出的资产url，在进行指纹识别的时候，还需要指定端口如443、80等 ，但是导出的url自带端口
建议该字段改成可留空吧

**Comment by TangGolang** [comment]
> ![image](https://private-user-images.githubusercontent.com/63778420/315209927-41d469cd-6dc1-4c9f-a457-be4b10b0e091.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwODAwMDYsIm5iZiI6MTcxMTA3OTcwNiwicGF0aCI6Ii82Mzc3ODQyMC8zMTUyMDk5MjctNDFkNDY5Y2QtNmRjMS00YzlmLWE0NTctYmU0YjEwYjBlMDkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDAzNTUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2YWNkYTJlNGM0NGVhNDhmNGRjMDAzYTk3NDUyNDE5MDkzZTk5M2RlMzZmNzM4YzJkOTEyOWRlMTQ1MjAzMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oRrw2E6kt_c-jfCc2WVN_H3K4STS3X1tFaBPjoi7GlQ) 类似从fofa导出的资产url，在进行指纹识别的时候，还需要指定端口如443、80等 ，但是导出的url自带端口 建议该字段改成可留空吧

感谢反馈，以列入更新计划，尽快改进。

**Comment by TangGolang** [comment]
该问题已在1.4.7版本进行了优化，默认扫描原目标的URL端口，同时可以自定义扫描端口范围： 

![image](https://github.com/TangGolang/TangGo/assets/46477721/a48b8ba0-f657-448c-be28-51178b789d64)

**Comment by a1most** [comment]
hello，我在使用tanggo时，代理页面翻页功能不正常显示，如图：
![image](https://github.com/TangGolang/TangGo/assets/34560797/c5f4b0cf-ae64-438a-99ef-eee799c2f08a)
无论是全屏或者缩放，都存在这个问题。
我的操作系统是：Windows 10 专业版 21H2

**Comment by yWillow** [comment]
> hello，我在使用tanggo时，代理页面翻页功能不正常显示，如图： ![image](https://private-user-images.githubusercontent.com/34560797/328362012-c5f4b0cf-ae64-438a-99ef-eee799c2f08a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyODI5MTYsIm5iZiI6MTcxNjI4MjYxNiwicGF0aCI6Ii8zNDU2MDc5Ny8zMjgzNjIwMTItYzVmNGIwY2YtYWU2NC00MzhhLTk5ZWYtZWVlNzk5YzJmMDhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDA5MTAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiNjExNjE4NGEyOWEzZWU1ZDk3NTkxNjc1NGYzODk1NGE5YjcxODVkMjUxMDI5NTNlNDZmMjA0YTIzZDUxOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fq3SntAIqj8RPJg1F5ZRks8c_eRhDuJNVMo-UwXWL6k) 无论是全屏或者缩放，都存在这个问题。 我的操作系统是：Windows 10 专业版 21H2

感谢反馈，已安排修复
