### ISSUE TITLE
【巴隔(bug)】人工客服清空聊天记录无效

### ISSUE THREAD

**Issue by Kge8686888** [TangGolang/TangGo#15]
Uploading 69e6d955de46f935c34ddab2a5ae2467.mp4…

**Comment by Kge8686888** [comment]
反馈群查看视频

**Comment by Kge8686888** [comment]
https://github.com/TangGolang/TangGo/assets/104627306/8015ff13-f059-44ae-9c6f-0aab09f3f9a8

**Comment by yWillow** [comment]
师傅您好，您反馈的 BUG 确实存在，技术部门给出的等级评为“中等BUG”，麻烦师傅联系工作人员 wx：_some_time，我们会邀请你加入用户群。

**Comment by Kge8686888** [comment]
你不能
加我
wx
吗
