### ISSUE TITLE
【BUG】编码解码工具导致数据覆盖丢失

### ISSUE THREAD

**Issue by Ms-yin** [TangGolang/TangGo#26]
TangGo版本：v.1.4.8
软件版本：V.1.0.6
复现步骤：
1.打开编码加密解密工具
2.选择除了base64编码外其余编码
3.在选择的编码选项框中输入数据
4.点击右上角新建一个编码框2
5.粘贴数据（手动输入不会）
6.回到编码框1 数据丢失

https://github.com/TangGolang/TangGo/assets/102912352/118fc699-59b3-4f97-8fc6-c480c105c375

**Comment by Kge8686888** [comment]
太强了~

**Comment by Ms-yin** [comment]
![image](https://github.com/TangGolang/TangGo/assets/102912352/4ab9108a-e375-4f94-a0b9-14baed53e402)
还会导致当前编码选择器被替换
