### ISSUE TITLE
【疑似bug】代理端口冲突

### ISSUE THREAD

**Issue by Kge8686888** [TangGolang/TangGo#28]
![844893d14ec7b182e63e180a481abec](https://github.com/user-attachments/assets/3dccabfd-cea0-4437-8e4c-1475456f4fd0)
代理的ip不一样，为什么端口显示进行了冲突呢，burp都不会这样

**Comment by TangGolang** [comment]
127.0.0.1:8080的代理服务地址设置的是“监听全部网卡”，等同于已经监听所有地址的8080端口了，故会提示端口占用。
