### ISSUE TITLE
【BUG】HTTP抓包测试工具数据包导入导出功能无法使用

### ISSUE THREAD

**Issue by soyum2222** [TangGolang/TangGo#3]
软件版本：V1.6.5
复现步骤：
1）使用HTTP抓包工具抓包
2）点击文件-点击导入/导出  无反应

![image](https://github.com/TangGolang/TangGo/assets/35021738/bdfa5073-ab30-424c-be25-617cae0460e6)

**Comment by yWillow** [comment]
师傅您好，您反馈的 BUG 确实存在，技术部门给出的等级评为“中等BUG”，麻烦师傅联系工作人员 wx：_some_time，我们会邀请你加入用户群。
