### ISSUE TITLE
自定义界面添加jar出现的BUG

### ISSUE THREAD

**Issue by h1d0ng9e** [TangGolang/TangGo#30]
1. arm 1.5.2版本，刚安装成功的时候 是可以正常使用的，关闭再打开 就出现了下图的bug

错误: 缺少 JavaFX 运行时组件, 需要使用该组件来运行此应用程序
![image](https://github.com/user-attachments/assets/18f0c65c-1dfd-4589-9cf7-50234a53d0fa)

2.        本地终端可以正常打开使用，arm版本

**Comment by TangGolang** [comment]
感谢师傅的反馈，请您参考下这篇文章的解决方案，https://www.cnblogs.com/jynszpd/p/15107813.html

在后面追加参数
`--module-path "你的javafx-sdk\lib" --add-modules javafx.controls,javafx.fxml` 
再运行，看看是否还存在此问题。
