### ISSUE TITLE
mac arm 版本 HTTP模糊测试工具一直显示启动时间

### ISSUE THREAD

**Issue by pyroxenites** [TangGolang/TangGo#31]
<img width="1781" alt="image" src="https://github.com/user-attachments/assets/a356830e-04c9-4399-93d8-63281d1b47ec">
mac arm 版本 HTTP模糊测试工具一直显示启动时间

**Comment by TangGolang** [comment]
抱歉，我们无法复现该问题，方便的话请提供您的macos的软硬件信息，如CPU型号、操作系统版本，以便我们复现和修正该问题。

**Comment by pyroxenites** [comment]
是不是这个系统原因😆
<img width="465" alt="image" src="https://github.com/user-attachments/assets/07440ba9-4fdd-49eb-9d50-b738450c0f46">

**Comment by TangGolang** [comment]
@pyroxenites 感谢师傅，我们排查下原因。

**Comment by eleveni386** [comment]
我也是这个问题， 启动模糊测试工具，一直显示启动中，我的系统也是M1， 版本15.0.1

**Comment by TangGolang** [comment]
@eleveni386 此bug已经修复，新版本1.6.3已更新上线，感谢您的反馈。

**Comment by TangGolang** [comment]
@pyroxenites 此bug已经修复，新版本1.6.3已更新上线，感谢您的反馈。
