### ISSUE TITLE
Web指纹识别模块URL识别问题

### ISSUE THREAD

**Issue by Unstoppable-yu** [TangGolang/TangGo#32]
Web指纹识别模块是不支持URL识别判断吗？
例如这里，我访问的是"http://www.baidu.com:8848/nacos/"，但是我代理抓包的是"http://www.baidu.com:8848/"
![01](https://github.com/user-attachments/assets/4f4b476e-ec6d-4447-9b57-f4c87857d87a)
![02](https://github.com/user-attachments/assets/41e6d1c4-dce9-4fe6-b957-5362386293cb)
我又试了一下，指纹编辑里面的，发现也是同样的情况
![图片](https://github.com/user-attachments/assets/731b69d7-6a7e-4710-b58d-a0985891d46d)

**Comment by TangGolang** [comment]
感谢反馈，目前的没有对存在二级目录的网站进行处理，后续版本将会改进。

**Comment by TangGolang** [comment]
已修复，请安装或更新主框架1.5.3版本，升级指纹识别工具到1.1.0版本。

示例如下：    

<img width="1025" alt="CF00EF20-7B85-457c-A0BE-EB403489D075" src="https://github.com/user-attachments/assets/5155510d-56fa-4305-8920-562fb9bd52da">    

<img width="1025" alt="B36E3BC0-F293-4500-89F4-FFCE9C160A87" src="https://github.com/user-attachments/assets/3000b274-07f0-4386-aad2-50b072b52a38">   

<img width="1025" alt="DB02593A-8ED9-4308-8F91-860A21ECA100" src="https://github.com/user-attachments/assets/ade21aa5-1f89-4a1d-a64f-7fc49573d48e">

**Comment by TangGolang** [comment]
@Unstoppable-yu 感谢您的反馈，请告诉我您的网络ID，我们将添加到我们的官网感谢名单。

**Comment by Unstoppable-yu** [comment]
好的，网络ID为Unstoppable
