### ISSUE TITLE
MAC 上面自己安装的java环境无法选择,以前的环境无法删除、内置的java版本应该再加个java8嘻嘻嘻

### ISSUE THREAD

**Issue by JiangJiYue** [TangGolang/TangGo#38]
MAC 上面自己安装的java环境无法选择,以前的环境无法删除、内置的java版本应该再加个java8嘻嘻嘻

**Comment by TangGolang** [comment]
@JiangJiYue 感谢师傅的反馈，后续考虑添加。自己安装的环境可以在这里添加的： 

![image](https://github.com/user-attachments/assets/184e1b96-010f-4305-8fd8-9c96abe72a6d)

**Comment by JiangJiYue** [comment]
谢谢师傅,MAC路径有点问题一开始没研究明白后面直接输入路径解决了
