### ISSUE TITLE
如何删除TangGo自带的框架工具？

### ISSUE THREAD

**Issue by eleveni386** [TangGolang/TangGo#39]
TangGo的第三方工具界面功能做的非常好，想着用TangGo来做工具箱是非常棒的，另外，已经下载安装的官方工具要如何删除呢？

**Comment by TangGolang** [comment]
@eleveni386 师傅，您好，已安装的工具可以在\resources\resources\app和\resources\resources\backend_services\bin中找到并删除，如果不知道路径，可以查看\resources\resources\backend_services\conf\app.xml中的路径映射。

自定义界面工具，可以在这里删除：
![image](https://github.com/user-attachments/assets/1ea25f42-da4e-4fab-bfee-d5d854fde3a4)
