### ISSUE TITLE
【优化建议】自定义字段名

### ISSUE THREAD

**Issue by Kge8686888** [TangGolang/TangGo#5]
HTTP模糊测试工具
![image](https://github.com/TangGolang/TangGo/assets/104627306/ec0c4a1c-5137-4693-9446-6f716d409aa8)
字段的名字不能自定义

**Comment by yWillow** [comment]
您好，非常感谢您的提议，产品部门给出的等级为“普通 建议”，麻烦师傅联系工作人员 wx：_some_time，我们会邀请你加入用户群。
