### ISSUE TITLE
【BUG】HTTP模糊测试导出的表格有特殊

### ISSUE THREAD

**Issue by Kge8686888** [TangGolang/TangGo#7]
![image](https://github.com/TangGolang/TangGo/assets/104627306/64449f26-1480-4ea0-918c-6ce5a625dfd2)

导出后
![image](https://github.com/TangGolang/TangGo/assets/104627306/8cadabb5-8fe1-4a2e-97a5-743005841765)
![image](https://github.com/TangGolang/TangGo/assets/104627306/1733b853-cf69-46b9-990e-a7b110ceb00c)
每个单元格中出现：

**Comment by TangGolang** [comment]
该字符是为解决cvs文件在excel中预览时，以0开头的字符串，如00012345的显示成12345而特意添加的，为的是避免用户在获取到某些数据后在excel表格中看不到0。
